config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  get 'home/lookup'
  root 'home#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require 'net/http'
    require 'json'
    @url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?CMC_PRO_API_KEY=fd04676f-2762-4500-9f39-c0290aa0c3c8&start=1&limit=100&convert=USD'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @coins = JSON.parse(@response)
  end
  def lookup
    require 'net/http'
    require 'json'
    @url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?CMC_PRO_API_KEY=fd04676f-2762-4500-9f39-c0290aa0c3c8&start=1&limit=100&convert=USD'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @lookup_coins = JSON.parse(@response)
    @input = params[:name_or_sym]
    if @input
      @input = @input.downcase
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/header_footer/_footer.html.erb
<!-- Footer -->
<footer class="mt-auto bg-dark text-white pt-4 pb-4">

  <!-- Footer Links -->
  <div class="container-fluid text-start text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-5 mt-md-0 mt-3">

        <!-- Content -->
        <h5 class="text-uppercase text-center fs-1">Rails Crypto</h5>
        <%# <p class="text-center"> organize your footer content.</p> %>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">
      <!-- Grid column -->
      <div class="col-md-2 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">company</h5>

        <ul class="list-unstyled">
          <li>
            <%= link_to "About Us", home_index_path, class:"text-decoration-none" %>
          </li>
          <li>
            <a href="#!" class="text-decoration-none">Term of use</a>
          </li>
          <%# <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li> %>
        </ul>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">support</h5>

        <ul class="list-unstyled">
          <li>
            <a href="readme" class="text-decoration-none">FAQ</a>
          </li>
          <li>
            <a href="#!" class="text-decoration-none" target="_blank">Request form</a>
          </li>
          <%# <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li> %>
        </ul>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Social</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!" class="text-decoration-none" target="_blank">Facebook</a>
          </li>
          <li>
            <a href="#!" class="text-decoration-none" target="_blank">Twitter</a>
          </li>
          <li>
            <a href="https://github.com/NguyenTungSon0503/RailsCrypto" class="text-decoration-none" target="_blank">Git Hub</a>
          </li>
          <%# <li>
            <a href="#!">Link 4</a>
          </li> %>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <br/>

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2022
    <a> RailsCrypto. All rights reserved</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/header_footer/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Rails Crypto', home_index_path, class: "navbar-brand align-top" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Search", home_lookup_path, class:"nav-link active"%>
        </li>

    <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link active"%>
        </li>
        <li class="nav-item">
          <%= link_to "Log Out", destroy_user_session_path, class:"nav-link active"%>
        </li>
    <% else %>

        <li class="nav-item">
          <%= link_to "Log In", new_user_session_path,class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path,class:"nav-link active" %>
        </li>
    <% end %>

        

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Symbol</th>
      <th scope="col">Price</th>
      <th scope="col">Volume</th>
    </tr>
  </thead>
  <tbody>
    <% for x in @coins['data'] %>   
            <tr>
                    <td><%= x['cmc_rank']%></td>
                    <td><%= x['name']%></td>
                    <td><%= x['symbol'] %></td>
                    <td>$<%= x['quote']['USD']['price']%></td>
                    <td><%= x['quote']['USD']['volume_24h']%></td>
            </tr>
    <% end %>
  </tbody>
</table>
    <%= render "header_footer/footer"%>

app/views/home/lookup.html.erb
<h2>Look Up a single coin Currency</h2>
<br>
<%=form_tag home_lookup_path, :method => 'GET' do%>
<%=text_field_tag 'name_or_sym', nil, placeholder: "Hay nhap vao ten hoac symbol", size: 30%>
<%= submit_tag "Search", class: "btn btn-success"%>
<% end %>
<br>
<% if @input %>
  <table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Symbol</th>
      <th scope="col">Price</th>
      <th scope="col">Volume</th>
    </tr>
  </thead>
  <tbody>
  <% for x in @lookup_coins['data']%>
<% if x['name'].downcase.include?(@input) %>
              <tr>
                    <td><%= x['cmc_rank']%></td>
                    <td><%= x['name']%></td>
                    <td><%= x['symbol'] %></td>
                    <td>$<%= x['quote']['USD']['price']%></td>
                    <td><%= x['quote']['USD']['volume_24h']%></td>
            </tr>
    <% elsif  x['symbol'].downcase.include?(@input) %>
                  <tr>
                    <td><%= x['cmc_rank']%></td>
                    <td><%= x['name']%></td>
                    <td><%= x['symbol'] %></td>
                    <td>$<%= x['quote']['USD']['price']%></td>
                    <td><%= x['quote']['USD']['volume_24h']%></td>
            </tr>
<% end %>
  </tbody>
<% end %>
<% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coins</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "header_footer/header"%>
    <%= yield %>

  </body>
</html>